# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Off Broadway Laundromat
email: dsprayer@minot.com
description: > # this means to ignore newlines until "baseurl:"
  Off Broadway Laundromat offers state-of-the-art equipment to take care of all
  your laundry needs. Sit back and relax while you wait with a cappuccino while
  you catch up on your emails while using our complimentary Wi-Fi. We are here
  to make laundry day something to look forward to.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.offbroadwaylaundromat.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
